- name: install apache2 and php packages
  tags: apache,httpd,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache2 service
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerAdmin'
    line: "#ServerAdmin somebody@somewhere.NET"
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644      
    
